modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="dimensional_corn_dog"
version="1.0.0"
displayName="Dimensional Corn Dog"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="jerry, MCreator"

[[dependencies.dimensional_corn_dog]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




