modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="dimensional_corn_dog"
version="1.0.4"
displayName="Dimensional Corn Dog"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://github.com/solojedi/DimensionalCornDogs/issues"
logoFile="logo.png"
authors="CoffeeHacker, MCreator"
description='''
Dimensional Teleportation Corn Dogs
'''

[[dependencies.dimensional_corn_dog]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




